import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { BarChart2, Users, Target, Briefcase, AlertCircle, CheckCircle, Coffee, Copy, Check } from 'lucide-react'
import { useSprintStore } from '../store/useSprintStore'
import { generateBriefings } from '../logic/briefing'
import { generateBriefingSummary } from '../logic/briefingAI'

const TAB_CONFIG = {
  team:    { icon: Users,     label: 'Team',    fullLabel: 'Team Brief',    description: 'Operational status for the engineering team' },
  pm:      { icon: Target,    label: 'PM',      fullLabel: 'PM Brief',      description: 'Risks, trade-offs, and escalations for the PM' },
  manager: { icon: Briefcase, label: 'Manager', fullLabel: 'Manager Brief', description: 'Delivery confidence and milestone risk' },
  standup: { icon: Coffee,    label: 'Standup', fullLabel: 'Standup',       description: 'Daily standup digest — ready to paste into Slack' },
}

const SEV_CONFIG = {
  ok:       { icon: CheckCircle,  color: 'var(--ok)',   bg: 'rgba(47,158,111,0.07)',  bd: 'rgba(47,158,111,0.16)' },
  warn:     { icon: AlertCircle,  color: 'var(--warn)', bg: 'rgba(160,120,48,0.07)',  bd: 'rgba(160,120,48,0.16)' },
  critical: { icon: AlertCircle,  color: 'var(--crit)', bg: 'rgba(185,64,64,0.07)',   bd: 'rgba(185,64,64,0.16)' },
}

function generateStandup(
  tasks: ReturnType<typeof useSprintStore.getState>['tasks'],
  team: ReturnType<typeof useSprintStore.getState>['team'],
  sprint: ReturnType<typeof useSprintStore.getState>['sprint'],
  escalations: ReturnType<typeof useSprintStore.getState>['escalations'],
) {
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })
  const completedPct = Math.round((sprint.completedPoints / sprint.committedPoints) * 100)
  const openEsc = escalations.filter(e => !e.resolved)
  const blocked = tasks.filter(t => t.status === 'blocked')

  const lines: string[] = []
  lines.push(`*Sprint Agent Standup — ${today}*`)
  lines.push(`*${sprint.name}* · ${sprint.daysRemaining} days left · ${completedPct}% complete`)
  lines.push('')
  lines.push('*Per-engineer update:*')

  for (const member of team) {
    const memberInProgress = tasks.filter(t => t.assigneeId === member.id && t.status === 'in-progress')
    const memberDone = tasks.filter(t => t.assigneeId === member.id && t.status === 'done')
    const memberBlocked = tasks.filter(t => t.assigneeId === member.id && t.status === 'blocked')
    const parts: string[] = []
    if (memberDone.length > 0) parts.push(`Done: ${memberDone.map(t => t.title.split(':')[0]).join(', ')}`)
    if (memberInProgress.length > 0) parts.push(`In progress: ${memberInProgress.map(t => t.title.split(':')[0]).join(', ')}`)
    if (memberBlocked.length > 0) parts.push(`Blocked: ${memberBlocked.map(t => t.title.split(':')[0]).join(', ')}`)
    if (parts.length === 0) parts.push(`No active tasks (${member.currentLoad}% load)`)
    lines.push(`\n*${member.name}* (${member.role})`)
    for (const p of parts) lines.push(`  ${p}`)
  }

  lines.push('')
  lines.push('*Sprint health:*')
  lines.push(`  Sprint goal: ${sprint.health === 'green' ? 'On track' : sprint.health === 'yellow' ? 'At risk' : 'In jeopardy'}`)
  if (blocked.length > 0) lines.push(`  ${blocked.length} task${blocked.length > 1 ? 's' : ''} blocked — needs PM attention`)
  if (openEsc.length > 0) lines.push(`  ${openEsc.length} open escalation${openEsc.length > 1 ? 's' : ''} requiring decisions`)
  lines.push(`  ${sprint.completedPoints}/${sprint.committedPoints} pts · ${sprint.daysRemaining} days remaining`)

  if (openEsc.length > 0) {
    lines.push('')
    lines.push('*Decisions needed from PM:*')
    openEsc.slice(0, 3).forEach(e => {
      lines.push(`  → ${e.taskTitle.split(':')[0]}: ${e.recommendation.slice(0, 80)}...`)
    })
  }

  lines.push('')
  lines.push('_Generated by Sprint Agent_')
  return lines.join('\n')
}

function StandupTab() {
  const { tasks, team, sprint, escalations } = useSprintStore()
  const [copied, setCopied] = useState(false)
  const standupText = generateStandup(tasks, team, sprint, escalations)
  const lines = standupText.split('\n')

  const handleCopy = () => {
    navigator.clipboard.writeText(standupText).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12, gap: 8 }}>
        <div>
          <div className="label" style={{ marginBottom: 3 }}>Daily Standup Digest</div>
          <p style={{ fontSize: 10, color: 'var(--t3)' }}>Agent-generated. Paste directly into Slack.</p>
        </div>
        <button
          onClick={handleCopy}
          className="btn btn-secondary"
          style={{
            gap: 5, flexShrink: 0,
            color: copied ? 'var(--ok)' : undefined,
            borderColor: copied ? 'rgba(47,158,111,0.22)' : undefined,
          }}
        >
          {copied ? <Check size={10} /> : <Copy size={10} />}
          {copied ? 'Copied!' : 'Copy'}
        </button>
      </div>

      <div style={{
        borderRadius: 7, background: 'var(--s2)', border: '1px solid var(--b1)',
        padding: '14px 16px',
        fontFamily: 'JetBrains Mono, monospace', fontSize: 11, lineHeight: 1.7,
      }}>
        {lines.map((line, i) => {
          const isHeader = line.startsWith('*Sprint Agent') || line.startsWith('*Per-engineer') || line.startsWith('*Sprint health') || line.startsWith('*Decisions')
          const isMemberName = line.startsWith('*') && !isHeader && line.endsWith(')')
          const isBlank = line === ''
          const isArrow = line.trim().startsWith('→')
          const isFooter = line.includes('_Generated')

          if (isBlank) return <div key={i} style={{ height: 6 }} />
          if (isHeader) return <div key={i} style={{ color: 'var(--t1)', fontWeight: 600, marginTop: 4 }}>{line.replace(/\*/g, '')}</div>
          if (isMemberName) return <div key={i} style={{ color: 'var(--act-t)', fontWeight: 600, marginTop: 8 }}>{line.replace(/\*/g, '')}</div>
          if (isArrow) return <div key={i} style={{ color: 'var(--ask-t)', paddingLeft: 8 }}>{line}</div>
          if (isFooter) return <div key={i} style={{ color: 'var(--t3)', marginTop: 8, fontStyle: 'italic' }}>{line.replace(/_/g, '')}</div>
          if (line.includes('Done:')) return <div key={i} style={{ color: 'var(--ok)', paddingLeft: 8 }}>{line}</div>
          if (line.includes('Blocked:')) return <div key={i} style={{ color: 'var(--crit)', paddingLeft: 8 }}>{line}</div>
          if (line.includes('In progress:')) return <div key={i} style={{ color: 'var(--act-t)', paddingLeft: 8 }}>{line}</div>
          return <div key={i} style={{ color: 'var(--t2)' }}>{line}</div>
        })}
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 10, fontSize: 10, color: 'var(--t3)' }}>
        <div className="live-dot" />
        Refreshes automatically as sprint state changes
      </div>
    </div>
  )
}

export function BriefingPanel() {
  const { tasks, team, sprint, escalations } = useSprintStore()
  const [activeTab, setActiveTab] = useState<'team' | 'pm' | 'manager' | 'standup'>('pm')
  const briefings = generateBriefings(tasks, team, sprint, escalations)
  const activeBrief = activeTab !== 'standup' ? briefings.find((b) => b.type === activeTab)! : null
  const [aiSummary, setAiSummary] = useState<string>('')
  const [aiLoading, setAiLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  // Fix #6: build copy text from active brief content
  const handleCopyBrief = () => {
    if (!activeBrief) return
    const summary = aiSummary || activeBrief.summary
    const items = activeBrief.items.map(item => `${item.label}: ${item.value}`).join('\n')
    const text = `${TAB_CONFIG[activeTab].fullLabel}\n\n${summary}\n\n${items}`
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  useEffect(() => {
    if (activeTab === 'standup') return
    setAiSummary('')
    setAiLoading(true)
    generateBriefingSummary(activeTab as 'team' | 'pm' | 'manager', tasks, team, sprint, escalations)
      .then(s => { setAiSummary(s); setAiLoading(false) })
      .catch(() => setAiLoading(false))
  }, [activeTab])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden' }}>
      {/* Header */}
      <div style={{ flexShrink: 0, padding: '13px 18px', borderBottom: '1px solid var(--b0)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
          <BarChart2 size={13} style={{ color: 'var(--act)' }} />
          <span data-feature-id="briefings-header" style={{ fontSize: 13, fontWeight: 700, color: 'var(--t1)', letterSpacing: '-0.015em' }}>Briefings</span>
        </div>
        <p style={{ fontSize: 11, color: 'var(--t3)' }}>Agent-generated briefings, tailored by role.</p>

        {/* Tabs — underline pattern */}
        <div className="tab-bar" style={{ marginTop: 12 }}>
          {(Object.entries(TAB_CONFIG) as [keyof typeof TAB_CONFIG, typeof TAB_CONFIG[keyof typeof TAB_CONFIG]][]).map(([key, cfg]) => {
            const Icon = cfg.icon
            const isActive = activeTab === key
            return (
              <button
                key={key}
                onClick={() => setActiveTab(key)}
                className={`tab-item${isActive ? ' tab-item-active' : ''}`}
              >
                <Icon size={10} />
                {cfg.label}
              </button>
            )
          })}
        </div>
      </div>

      {/* Content */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '14px 18px' }}>
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 7 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            transition={{ duration: 0.18 }}
          >
            {activeTab === 'standup' ? (
              <StandupTab />
            ) : activeBrief ? (
              <>
                {/* Summary — AI-generated if available, else deterministic */}
                <div style={{ marginBottom: 14 }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 6, marginBottom: 6 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                      <div className="label">{TAB_CONFIG[activeTab].description}</div>
                      {(aiSummary || aiLoading) && (
                        <span style={{ fontSize: 9, fontWeight: 700, padding: '1px 5px', borderRadius: 3, background: 'var(--act-bg)', border: '1px solid var(--act-bd)', color: 'var(--act-t)', letterSpacing: '0.05em' }}>
                          AI
                        </span>
                      )}
                    </div>
                    {/* Fix #6: copy button */}
                    {!aiLoading && (
                      <button
                        onClick={handleCopyBrief}
                        className="btn btn-secondary"
                        style={{ gap: 4, padding: '3px 8px', fontSize: 10, flexShrink: 0, color: copied ? 'var(--ok)' : undefined, borderColor: copied ? 'rgba(47,158,111,0.22)' : undefined }}
                      >
                        {copied ? <Check size={9} /> : <Copy size={9} />}
                        {copied ? 'Copied!' : 'Copy'}
                      </button>
                    )}
                  </div>
                  {aiLoading ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 5, paddingBottom: 12, borderBottom: '1px solid var(--b1)' }}>
                      {[80, 65, 45].map((w, i) => <div key={i} className="skeleton" style={{ height: 10, width: `${w}%` }} />)}
                    </div>
                  ) : (
                    <p style={{ fontSize: 12, color: 'var(--t1)', lineHeight: 1.65, borderBottom: '1px solid var(--b1)', paddingBottom: 12 }}>
                      {aiSummary || activeBrief.summary}
                    </p>
                  )}
                </div>

                {/* Items — divide-y pattern, no card-on-card */}
                <div>
                  {activeBrief.items.map((item, i) => {
                    const severity = item.severity ?? 'ok'
                    const sev = SEV_CONFIG[severity]
                    const SevIcon = sev.icon
                    return (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, y: 4 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.04 }}
                        style={{
                          display: 'flex', alignItems: 'flex-start', gap: 10,
                          padding: '10px 0',
                          borderBottom: i < activeBrief.items.length - 1 ? '1px solid var(--b0)' : 'none',
                          borderLeft: `3px solid ${sev.color}`,
                          paddingLeft: 10,
                        }}
                      >
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 3 }}>
                            {/* #7 — severity icon + label together, icon slightly larger */}
                            <SevIcon size={10} style={{ color: sev.color, flexShrink: 0 }} strokeWidth={2} />
                            <span style={{ fontSize: 10, fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.10em', color: sev.color }}>{item.label}</span>
                          </div>
                          <p style={{ fontSize: 11, color: 'var(--t2)', lineHeight: 1.6 }}>{item.value}</p>
                        </div>
                      </motion.div>
                    )
                  })}
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 14, fontSize: 10, color: 'var(--t3)' }}>
                  <div className="live-dot" />
                  Updated in real-time
                </div>
              </>
            ) : null}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  )
}
