import { useState, useEffect, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  X, Zap, ArrowRight, ArrowLeft,
  ShieldAlert, Inbox, Activity,
  BarChart2, Slack, GitBranch,
  Brain, Target, Users, MessageCircle,
  TrendingUp, CheckCircle, Wand2,
} from 'lucide-react'
import { useSprintStore } from '../store/useSprintStore'
import { useTour } from '../hooks/useTour'

const SESSION_KEY = 'libra-guide-v2'

/* ── Slide definitions ─────────────────────────────── */
const SLIDES = [
  {
    id: 'intro',
    tag: null,
    headline: 'An AI that runs your sprint.',
    sub: 'Sprint Agent is not a dashboard. It is an autonomous operator — it triages tasks the moment they arrive, assigns them to the right engineer, monitors capacity, resolves blockers, and escalates only when it genuinely cannot proceed without you.',
    features: null,
    stat: { value: '0', label: 'button clicks to triage a task' },
    cta: null,
    accentColor: 'var(--act)',
  },
  {
    id: 'autonomous',
    tag: 'Core Loop',
    headline: 'Intake → Triage → Assign. Automatically.',
    sub: 'Submit a request in plain English. The agent triages it with AI reasoning, scores it 0–100, decides ACT / ASK / ESCALATE, and assigns it to the best-fit engineer — all before you finish typing your next message.',
    features: [
      { icon: Zap,           text: 'Auto-triages every task on creation — no button click' },
      { icon: Brain,         text: 'Groq-powered reasoning with specific ASK questions' },
      { icon: Users,         text: 'Assigns based on skills × current load × sprint goal fit' },
    ],
    stat: { value: '<3s', label: 'from "submit" to assigned task' },
    cta: { label: 'Try it → Intake', view: 'intake' },
    accentColor: 'var(--act)',
  },
  {
    id: 'decisions',
    tag: 'Decision System',
    headline: 'ACT. ASK. ESCALATE.',
    sub: 'Every task gets exactly one verdict. ACT when the agent can safely proceed. ASK when it needs one specific answer before acting. ESCALATE when the decision carries risk or authority the agent doesn\'t have. The boundary is explicit and auditable.',
    features: [
      { icon: CheckCircle,  text: 'ACT: clarity ≥ 3, risk manageable, reversible outcome' },
      { icon: MessageCircle,text: 'ASK: generates a specific, answerable blocking question' },
      { icon: ShieldAlert,  text: 'ESCALATE: PII risk, scope conflict, irreversible action' },
    ],
    stat: { value: '3', label: 'possible verdicts, always explicit' },
    cta: { label: 'See decisions → Triage Queue', view: 'triage' },
    accentColor: '#8B4300',
  },
  {
    id: 'loop',
    tag: 'Autonomous Loop',
    headline: 'The agent monitors. You don\'t have to.',
    sub: 'Every 60 seconds the agent checks capacity, blocked tasks, velocity, and unresolved escalations. When Dev Mehta hits 90% load, it reassigns his lowest-priority task autonomously. When a task is blocked 2+ hours, it re-assigns the dependency — not just alerts.',
    features: [
      { icon: Users,        text: 'Rebalances overloaded engineers by actually reassigning tasks' },
      { icon: GitBranch,    text: 'Resolves blocked tasks by moving dependency owners' },
      { icon: TrendingUp,   text: 'Flags velocity deficit and recommends de-scoping' },
    ],
    stat: { value: '60s', label: 'monitoring interval, no server needed' },
    cta: { label: 'Watch it → Agent Feed', view: 'sprint' },
    accentColor: 'var(--ok)',
  },
  {
    id: 'intelligence',
    tag: 'Sprint Intelligence',
    headline: 'Backlog from a brief. Real issues from GitHub.',
    sub: 'Describe what you want to ship in one paragraph — the agent generates a full prioritized backlog with assignments. Or paste any GitHub repo URL and it pulls real open issues, triages them all, and assigns them. Your sprint is populated before your standup ends.',
    features: [
      { icon: Wand2,        text: 'Sprint Planner: natural language → full prioritized backlog' },
      { icon: GitBranch,    text: 'GitHub import: real issues, auto-triaged, auto-assigned' },
      { icon: Target,       text: 'Goal alignment: flags tasks that don\'t serve the sprint goal' },
    ],
    stat: { value: '1', label: 'sentence to generate an entire sprint backlog' },
    cta: { label: 'Generate a backlog → Sprint Planner', view: 'planner' },
    accentColor: 'var(--act)',
  },
  {
    id: 'comms',
    tag: 'Communication',
    headline: 'The agent reaches your team. You don\'t have to relay.',
    sub: 'Escalations post to Slack the moment they happen — not after you notice them. The standup digest writes and posts itself at 9am. Briefings are generated by role so the PM, team, and manager each see exactly what matters to them.',
    features: [
      { icon: Slack,        text: 'Escalations → Slack instantly, with task + recommendation' },
      { icon: BarChart2,    text: 'Role-based briefings: Team / PM / Manager / Standup' },
      { icon: Zap,          text: 'Daily standup auto-posts at 9am on first app open' },
    ],
    stat: { value: '0', label: 'manual standup updates needed' },
    cta: { label: 'See briefings', view: 'briefings' },
    accentColor: '#4A154B',
  },
  {
    id: 'analytics',
    tag: 'Analytics & Audit',
    headline: 'Every decision is visible. Nothing is a black box.',
    sub: 'The live feed logs every agent action with reasoning in plain English. The burndown shows you whether you\'re behind pace. Velocity trends across past sprints. And every ACT decision that led to a completed task improves the agent\'s calibration over time.',
    features: [
      { icon: Activity,     text: 'Live decision log — every action narrated in first person' },
      { icon: TrendingUp,   text: 'Burndown + velocity trend across 3 archived sprints' },
      { icon: Users,        text: 'Team utilization + agent calibration accuracy over time' },
    ],
    stat: { value: '85%', label: 'ACT decision accuracy (calibrated from past sprints)' },
    cta: { label: 'See the data → Sprint Review', view: 'review' },
    accentColor: 'var(--warn)',
  },
  {
    id: 'start',
    tag: 'Get started',
    headline: 'Three things to try in the next 5 minutes.',
    sub: null,
    features: null,
    steps: [
      { num: '01', icon: Inbox,      color: 'var(--act)',  title: 'Submit a request to Intake', desc: 'Try: "Salesforce connector returning stale data on pipeline records." Watch the agent triage + assign without you doing anything else.' },
      { num: '02', icon: ShieldAlert, color: 'var(--crit)', title: 'Resolve an escalation', desc: 'Open Escalations. Two items need your call. Approve one — the agent re-triages automatically and resumes.' },
      { num: '03', icon: Wand2,      color: 'var(--ok)',   title: 'Generate a sprint backlog', desc: 'Open Sprint Planner. Paste a product brief. Get a full prioritized backlog with assignments in 5 seconds.' },
    ],
    stat: null,
    cta: { label: 'Open Intake and start', view: 'intake' },
    accentColor: 'var(--act)',
  },
]

const slideVariants = {
  enter: (dir: number) => ({ x: dir > 0 ? 40 : -40, opacity: 0 }),
  center: { x: 0, opacity: 1 },
  exit: (dir: number) => ({ x: dir < 0 ? 40 : -40, opacity: 0 }),
}

export function GuidedOverlay() {
  const { setView } = useSprintStore()
  const { start: startTour } = useTour()
  const [visible, setVisible]   = useState(false)
  const [page, setPage]         = useState(0)
  const [direction, setDirection] = useState(1)

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const forced = params.get('guide') === 'true'
    const seen   = localStorage.getItem(SESSION_KEY)

    if (forced) {
      // ?guide=true resets and shows — but strip the param from URL immediately
      // so a plain refresh doesn't re-trigger it
      localStorage.removeItem(SESSION_KEY)
      const clean = window.location.pathname + window.location.hash
      window.history.replaceState(null, '', clean)
    }

    if (!seen || forced) setVisible(true)
  }, [])

  const dismiss = useCallback((goTo?: string) => {
    localStorage.setItem(SESSION_KEY, '1')
    setVisible(false)
    if (goTo) setTimeout(() => setView(goTo as any), 300)
  }, [setView])

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (!visible) return
      if (e.key === 'Escape') dismiss()
      if (e.key === 'ArrowRight') goNext()
      if (e.key === 'ArrowLeft')  goPrev()
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [visible, page, dismiss])

  const goNext = () => {
    if (page < SLIDES.length - 1) { setDirection(1); setPage(p => p + 1) }
  }
  const goPrev = () => {
    if (page > 0) { setDirection(-1); setPage(p => p - 1) }
  }

  const slide = SLIDES[page]

  return (
    <AnimatePresence>
      {visible && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            onClick={() => dismiss()}
            style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.60)', zIndex: 10000, backdropFilter: 'none' }}
          />

          {/* Modal — outer div owns position/size; motion.div owns animation only */}
          <div style={{
            position: 'fixed', top: '50%', left: '50%',
            transform: 'translate(-50%, -50%)',
            zIndex: 10001,
            width: 'min(580px, calc(100vw - 32px))',
            maxHeight: 'calc(100vh - 40px)',
            display: 'flex', flexDirection: 'column',
            borderRadius: 14, overflow: 'hidden',
            boxShadow: '0 32px 80px rgba(0,0,0,0.30)',
          }}>
          <motion.div
            initial={{ opacity: 0, scale: 0.93 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            transition={{ type: 'spring', stiffness: 260, damping: 24 }}
            style={{
              background: 'var(--card)', border: '1px solid var(--border)',
              borderRadius: 14,
              display: 'flex', flexDirection: 'column',
              flex: 1, minHeight: 0, overflow: 'hidden',
            }}
          >
            {/* Progress bar */}
            <div style={{ height: 2, background: 'var(--muted)' }}>
              <motion.div
                style={{ height: '100%', background: slide.accentColor }}
                animate={{ width: `${((page + 1) / SLIDES.length) * 100}%` }}
                transition={{ duration: 0.4, ease: 'easeOut' }}
              />
            </div>

            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 20px', borderBottom: '1px solid var(--border)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ width: 20, height: 20, borderRadius: 4, background: 'var(--act)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Zap size={10} color="#fff" strokeWidth={2.5} />
                </div>
                <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--foreground)', letterSpacing: '-0.015em' }}>Sprint Agent</span>
                {slide.tag && (
                  <span style={{ fontSize: 10, fontWeight: 700, padding: '1px 7px', borderRadius: 10, background: 'var(--muted)', border: '1px solid var(--border)', color: 'var(--muted-foreground)', letterSpacing: '0.03em' }}>
                    {slide.tag}
                  </span>
                )}
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <span style={{ fontSize: 10, color: 'var(--muted-foreground)', fontFamily: 'JetBrains Mono, monospace' }}>
                  {page + 1} / {SLIDES.length}
                </span>
                <button onClick={() => dismiss()} style={{ background: 'transparent', border: 'none', cursor: 'pointer', color: 'var(--muted-foreground)', display: 'flex', padding: 4, borderRadius: 4, transition: 'color 0.1s' }}
                  onMouseEnter={e => (e.currentTarget.style.color = 'var(--foreground)')}
                  onMouseLeave={e => (e.currentTarget.style.color = 'var(--muted-foreground)')}
                >
                  <X size={14} strokeWidth={1.5} />
                </button>
              </div>
            </div>

            {/* Slide content */}
            <div style={{ flex: 1, overflowY: 'auto', position: 'relative', minHeight: 0 }}>
              <AnimatePresence mode="wait" custom={direction}>
                <motion.div
                  key={page}
                  custom={direction}
                  variants={slideVariants}
                  initial="enter"
                  animate="center"
                  exit="exit"
                  transition={{ duration: 0.22, ease: [0.16, 1, 0.3, 1] }}
                  style={{ padding: '24px 24px 20px' }}
                >
                  {/* Headline */}
                  <h2 style={{ fontSize: 20, fontWeight: 800, color: 'var(--foreground)', letterSpacing: '-0.025em', lineHeight: 1.25, marginBottom: 10 }}>
                    {slide.headline}
                  </h2>

                  {/* Sub */}
                  {slide.sub && (
                    <p style={{ fontSize: 12, color: 'var(--muted-foreground)', lineHeight: 1.7, marginBottom: 18, maxWidth: 480 }}>
                      {slide.sub}
                    </p>
                  )}

                  {/* Features list */}
                  {slide.features && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 18 }}>
                      {slide.features.map((f, i) => {
                        const Icon = f.icon
                        return (
                          <motion.div key={i}
                            initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: i * 0.08 }}
                            style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 12px', borderRadius: 7, background: 'var(--muted)', border: '1px solid var(--border)' }}
                          >
                            <div style={{ width: 24, height: 24, borderRadius: 5, background: 'var(--card)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                              <Icon size={12} style={{ color: slide.accentColor }} strokeWidth={1.5} />
                            </div>
                            <span style={{ fontSize: 12, color: 'var(--foreground)', fontWeight: 500 }}>{f.text}</span>
                          </motion.div>
                        )
                      })}
                    </div>
                  )}

                  {/* Steps (last slide) */}
                  {slide.steps && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 9, marginBottom: 8 }}>
                      {slide.steps.map((s, i) => {
                        const Icon = s.icon
                        return (
                          <motion.div key={i}
                            initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.1 }}
                            style={{ display: 'flex', gap: 12, padding: '11px 13px', borderRadius: 8, background: 'var(--muted)', border: '1px solid var(--border)' }}
                          >
                            <div style={{ display: 'flex', alignItems: 'center', gap: 7, flexShrink: 0 }}>
                              <span style={{ fontSize: 9, fontWeight: 900, color: s.color, fontFamily: 'JetBrains Mono, monospace', letterSpacing: '0.06em', width: 18 }}>{s.num}</span>
                              <div style={{ width: 26, height: 26, borderRadius: 6, background: 'var(--card)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                <Icon size={13} style={{ color: s.color }} strokeWidth={1.5} />
                              </div>
                            </div>
                            <div>
                              <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--foreground)', letterSpacing: '-0.01em', marginBottom: 2 }}>{s.title}</div>
                              <p style={{ fontSize: 11, color: 'var(--muted-foreground)', lineHeight: 1.55, margin: 0 }}>{s.desc}</p>
                            </div>
                          </motion.div>
                        )
                      })}
                    </div>
                  )}

                  {/* Stat callout */}
                  {slide.stat && (
                    <div style={{ display: 'inline-flex', alignItems: 'baseline', gap: 6, padding: '8px 12px', borderRadius: 7, background: `${slide.accentColor}12`, border: `1px solid ${slide.accentColor}30` }}>
                      <span style={{ fontSize: 22, fontWeight: 900, color: slide.accentColor, fontFamily: 'JetBrains Mono, monospace', lineHeight: 1, letterSpacing: '-0.03em' }}>
                        {slide.stat.value}
                      </span>
                      <span style={{ fontSize: 11, color: 'var(--muted-foreground)', fontWeight: 500 }}>
                        {slide.stat.label}
                      </span>
                    </div>
                  )}
                </motion.div>
              </AnimatePresence>
            </div>

            {/* Footer */}
            <div style={{ padding: '12px 20px 18px', borderTop: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              {/* Dot indicators */}
              <div style={{ display: 'flex', gap: 5 }}>
                {SLIDES.map((_, i) => (
                  <button key={i} onClick={() => { setDirection(i > page ? 1 : -1); setPage(i) }}
                    style={{
                      height: 6, borderRadius: 3, border: 'none', cursor: 'pointer', padding: 0,
                      width: i === page ? 20 : 6,
                      background: i === page ? slide.accentColor : 'var(--border)',
                      transition: 'width 0.25s, background 0.15s',
                    }}
                  />
                ))}
              </div>

              {/* Navigation */}
              <div style={{ display: 'flex', gap: 7 }}>
                {page > 0 && (
                  <button onClick={goPrev} className="btn btn-secondary" style={{ gap: 5, padding: '5px 11px' }}>
                    <ArrowLeft size={11} strokeWidth={1.5} /> Prev
                  </button>
                )}
                {page < SLIDES.length - 1 ? (
                  <button onClick={goNext} className="btn btn-primary" style={{ gap: 5, padding: '5px 13px', background: slide.accentColor }}>
                    Next <ArrowRight size={11} strokeWidth={2} />
                  </button>
                ) : (
                  <>
                    <button
                      onClick={() => {
                        dismiss()
                        setTimeout(() => startTour((v) => setView(v as any)), 200)
                      }}
                      className="btn btn-secondary"
                      style={{ gap: 5 }}
                    >
                      Contextual tour
                    </button>
                    <button onClick={() => dismiss(slide.cta?.view)} className="btn btn-primary" style={{ gap: 5, background: 'var(--act)' }}>
                      {slide.cta?.label} <ArrowRight size={11} strokeWidth={2} />
                    </button>
                  </>
                )}
              </div>
            </div>

            {/* Keyboard hint */}
            <div style={{ textAlign: 'center', paddingBottom: 10, fontSize: 9, color: 'var(--muted-foreground)', fontFamily: 'JetBrains Mono, monospace', letterSpacing: '0.04em' }}>
              ← → arrow keys to navigate · Esc to close
            </div>
          </motion.div>
          </div>
        </>
      )}
    </AnimatePresence>
  )
}
