import type { Task, TeamMember, Sprint, EscalationItem } from '../types'

/** Generates the plain-text standup digest — extracted so it can be used in Slack posting. */
export function generateStandupText(
  tasks: Task[],
  team: TeamMember[],
  sprint: Sprint,
  escalations: EscalationItem[],
): string {
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })
  const pct = Math.round((sprint.completedPoints / sprint.committedPoints) * 100)
  const openEsc = escalations.filter(e => !e.resolved)
  const blocked = tasks.filter(t => t.status === 'blocked')
  const lines: string[] = []

  lines.push(`*Sprint Agent Standup — ${today}*`)
  lines.push(`*${sprint.name}* · ${sprint.daysRemaining} days left · ${pct}% complete`)
  lines.push('')
  lines.push('*Per-engineer update:*')

  for (const member of team) {
    const done = tasks.filter(t => t.assigneeId === member.id && t.status === 'done')
    const inProgress = tasks.filter(t => t.assigneeId === member.id && t.status === 'in-progress')
    const memberBlocked = tasks.filter(t => t.assigneeId === member.id && t.status === 'blocked')
    const parts: string[] = []
    if (done.length) parts.push(`Done: ${done.map(t => t.title.split(':')[0]).join(', ')}`)
    if (inProgress.length) parts.push(`In progress: ${inProgress.map(t => t.title.split(':')[0]).join(', ')}`)
    if (memberBlocked.length) parts.push(`Blocked: ${memberBlocked.map(t => t.title.split(':')[0]).join(', ')}`)
    if (!parts.length) parts.push(`No active tasks (${member.currentLoad}% load)`)
    lines.push(`\n*${member.name}* (${member.role})`)
    for (const p of parts) lines.push(`  ${p}`)
  }

  lines.push('')
  lines.push('*Sprint health:*')
  lines.push(`  Goal: ${sprint.health === 'green' ? 'On track' : sprint.health === 'yellow' ? 'At risk' : 'In jeopardy'}`)
  if (blocked.length) lines.push(`  ${blocked.length} task${blocked.length > 1 ? 's' : ''} blocked — needs PM attention`)
  if (openEsc.length) lines.push(`  ${openEsc.length} open escalation${openEsc.length > 1 ? 's' : ''} requiring decisions`)
  lines.push(`  ${sprint.completedPoints}/${sprint.committedPoints} pts · ${sprint.daysRemaining} days remaining`)

  if (openEsc.length) {
    lines.push('')
    lines.push('*Decisions needed from PM:*')
    openEsc.slice(0, 3).forEach(e => lines.push(`  → ${e.taskTitle.split(':')[0]}: ${e.recommendation.slice(0, 80)}...`))
  }

  lines.push('\n_Generated by Sprint Agent_')
  return lines.join('\n')
}

/** Posts the standup text to Slack as a formatted message. */
export async function postStandupToSlack(text: string, webhookUrl: string): Promise<void> {
  await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      blocks: [
        { type: 'section', text: { type: 'mrkdwn', text: text } },
        { type: 'context', elements: [{ type: 'mrkdwn', text: 'Posted automatically by Sprint Agent at 9am' }] },
      ],
    }),
  })
}
